import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import '../config/api.dart';
import '../domain/attendance.dart';
import '../domain/attendance_record.dart';

class AttendanceProvider with ChangeNotifier {
  List<AttendanceSubject> _subjects = [];
  List<AttendanceSubject> get subjects => _subjects;

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  /// Fetches subjects for the lecturer using Api config and query parameters
  Future<void> fetchLecturerSubjects(int lecturerId) async {
    _isLoading = true;
    notifyListeners();

    try {
      // Using Api.lecturerSubjects consistent with your ModuleProvider style
      final response = await http.get(
        Uri.parse("${Api.lecturerSubjects}?user_id=$lecturerId")
      );

      if (response.statusCode == 200) {
        final Map<String, dynamic> data = jsonDecode(response.body);
        final List<dynamic> subjectList = data['data'];

        _subjects = subjectList.map((json) => AttendanceSubject.fromJson(json)).toList();
      }
    } catch (e) {
      print("Error fetching attendance data: $e");
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Generates attendance and stores it in the database via Laravel API
  Future<String?> generateAttendance({
    required int sectionId,
    required double lat,
    required double lng,
    required String date,
    required String time,
  }) async {
    _isLoading = true;
    notifyListeners();

    try {
      // Logic: Use the Api class for the endpoint (Assumes Api.generateAttendance is defined)
      // If not defined, use Uri.parse("${Api.baseUrl}/attendance/store")
      final response = await http.post(
        Uri.parse(Api.generateAttendance), 
        headers: {"Content-Type": "application/json"},
        body: jsonEncode({
          'section_id': sectionId,
          'geo_lat': lat,
          'geo_long': lng,
          'radius': 500, // Constant radius
          'date': date,
          'time': time,
        }),
      );

      if (response.statusCode == 201 || response.statusCode == 200) {
        final resData = jsonDecode(response.body);
        return resData['code']; // The 6-digit code generated by Laravel
      }
    } catch (e) {
      print("Error generating attendance: $e");
    } finally {
      _isLoading = false;
      notifyListeners();
    }
    return null;
  }

  // --- Pusat ADAB Extensions ---
  
  // Inside AttendanceProvider.dart

 // --- YOUR PART: PUSAT ADAB & GRADING (Project Lead) ---

  // 1. Define the student list (Fixes image_1bad16.png)
  List<AttendanceRecord> _attendanceRecords = []; 
  List<AttendanceRecord> get attendanceRecords => _attendanceRecords;

  // 2. Fetch Modules from Bookings (For image_1acc8f.png)
  Future<void> fetchPusatAdabSessions() async {
      _isLoading = true;
      notifyListeners();
      try {
        final response = await http.get(Uri.parse("${Api.baseUrl}/pusat-adab/modules"));
        
        if (response.statusCode == 200) {
          List data = json.decode(response.body);
          // This will now only contain 'published' modules
          _subjects = data.map((item) => AttendanceSubject.fromJson(item)).toList();
        }
      } catch (e) {
        debugPrint("Error: $e");
      } finally {
        _isLoading = false;
        notifyListeners();
      }
    }

  List<dynamic> _presentStudents = [];
  List<dynamic> get presentStudents => _presentStudents;

  Future<void> fetchPresentStudents(int moduleId) async {
    _isLoading = true;
    notifyListeners();
    try {
      final response = await http.get(Uri.parse("${Api.baseUrl}/pusat-adab/modules/$moduleId/present"));
      if (response.statusCode == 200) {
        _presentStudents = json.decode(response.body);
      }
    } catch (e) {
      print("Error fetching students: $e");
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}